routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');


Auth::routes();

Route::group([
	'prefix' => 'admin',
	'as' => 'admin.',
	'namespace' => 'Admin',
	'middleware' => ['auth']
], function () {
	Route::get('/home', 'HomeController@index')->name('home');
	Route::group( [
		'prefix'    => 'author',
		'as'        => 'authors.',
	], function () {
		Route::get( '/', 'AuthorController@index' )->name( 'home' );
		Route::get( '/show/{author}', 'AuthorController@show' )->name( 'show' );
		Route::get( '/create', 'AuthorController@create' )->name( 'create' );
		Route::post( '/store', 'AuthorController@store' )->name( 'store' );
		Route::get( '/{author}/edit', 'AuthorController@edit' )->name( 'edit' );
		Route::put( '/{author}/update', 'AuthorController@update' )->name( 'update' );
		Route::delete( '/{author}/delete', 'AuthorController@destroy' )->name( 'delete' );
	});

	Route::group( [
		'prefix'    => 'book',
		'as'        => 'books.',
	], function () {
		Route::get( '/', 'BookController@index' )->name( 'index' );
		Route::get( '/ajax', 'BookController@index' )->name( 'searchAjax' );
		Route::get( '/show/{book}', 'BookController@show' )->name( 'show' );
		Route::get( '/create', 'BookController@create' )->name( 'create' );
		Route::post( '/store', 'BookController@store' )->name( 'store' );
		Route::get( '/{book}/edit', 'BookController@edit' )->name( 'edit' );
		Route::put( '/{book}/update', 'BookController@update' )->name( 'update' );
		Route::delete( '/{book}/delete', 'BookController@destroy' )->name( 'delete' );
	});

	Route::group( [
		'prefix'    => 'category',
		'as'        => 'categories.',
	], function () {
		Route::get( '/', 'CategoryController@index' )->name( 'index' );
		Route::get( '/show/{category}', 'CategoryController@show' )->name( 'show' );
		Route::get( '/create', 'CategoryController@create' )->name( 'create' );
		Route::post( '/store', 'CategoryController@store' )->name( 'store' );
		Route::get( '/{category}/edit', 'CategoryController@edit' )->name( 'edit' );
		Route::put( '/{category}/update', 'CategoryController@update' )->name( 'update' );
		Route::delete( '/{category}/delete', 'CategoryController@destroy' )->name( 'delete' );
	});
  });

app/Http/Controllers/Admin/BookController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entity\Author;
use App\Entity\Book;
use App\Entity\Category;
use App\Entity\BookCategory;
use App\Http\Requests\Book\CreateBookRequest;
use App\Services\BookService;
use Exception;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\Response;

class BookController extends Controller
{

	/**
	 * @var BookService
	 */
	private $service;

	public function __construct(BookService $service)
	{

		$this->service = $service;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @param Request $request
	 *
	 * @return Response
	 * @throws \Throwable
	 */
    public function index(Request $request)
    {
	    $query = Book::with( ['categories', 'author'] )->get();

	    if($request->ajax()) {
		    if ( ! empty( $value = $request->get( 'author' ) ) ) {
			    $authors = Author::authorLike( 'surname', $value );
			    $query = Book::with( [ 'author' ] )
			                 ->whereIn( 'author_id', $this->service->getIds($authors))->get();
		    }
		    if ( ! empty( $value = $request->get( 'category' ) ) ) {
			    $categories = Category::categoryLike('name', $value);
			    $bookCategories = BookCategory::whereIn( 'category_id', $this->service->getIds($categories) )->get();
			    $query = Book::whereIn( 'id', $this->service->getBookIds($bookCategories))->get();
		    }
		    $books = $query;
		    return view( 'admin.books.searchAjax', compact( 'books' ))->render();
	    }else{
		    $books = $query;
		    return view( 'admin.books.index', compact( 'books' ) );
	    }
    }

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return void
	 */
    public function create()
    {
	    $categories = Category::all();
	    $authors = Author::all();
	    $catArray = [];
	    return view('admin.books.create', compact('categories', 'authors', 'catArray'));
    }

	/**
	 * Store a newly created resource in storage.
	 * @param CreateBookRequest $request
	 * @return Response
	 */
    public function store(CreateBookRequest $request)
    {
	    $book = Book::create(
		    [
			    'name'  => $request['name'],
			    'description' => $request['description'],
			    'link' => ' ',
			    'author_id' => $request['author'],
		    ]
	    );
	    $this->service->createBookCategory($request['categories'], $book);
	    $this->service->fileHandle($request, $book);

	    return redirect()->route('admin.books.show', $book);
    }

	/**
	 * Display the specified resource.
	 *
	 * @param Book $book
	 *
	 * @return Response
	 */
    public function show(Book $book)
    {
	    return view('admin.books.show', compact('book'));
    }

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param Book $book
	 *
	 * @return Response
	 */
    public function edit(Book $book)
    {
	    return view('admin.books.edit', compact('book'));
    }

	/**
	 * Update the specified resource in storage.
	 *
	 * @param CreateBookRequest $request
	 * @param Book $book
	 *
	 * @return Response
	 */
    public function update(CreateBookRequest $request, Book $book)
    {
	    $book->update(
		    [
			    'name'  => $request['name'],
			    'description' => $request['description'],
		    ]
	    );
	    $path = null;
	    $image = $request->file('link');
	    if ($request['link'] !== null){
		    $new_name = rand() . '.' . $image->getClientOriginalExtension();
		    $image->move(public_path('build/books'), $new_name);
		    $path = '/build/books/' . $new_name;
		    $book->update(['link' => $path]);
	    }
	    return redirect()->route('admin.books.show', $book);
    }

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param Book $book
	 *
	 * @return Response
	 * @throws Exception
	 */
    public function destroy(Book $book)
    {
	    $book->delete();

	    return redirect()->route('admin.books.index');
    }
}

resources/views/admin/books/_nav.blade.php
@include ('admin._nav', ['page' => 'users'])

resources/views/admin/books/create.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.users._nav')

    <form method="POST" action="{{ route('admin.books.store') }}" enctype="multipart/form-data">
        @csrf

        <div class="form-group">
            <label for="name" class="col-form-label">Name</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" {{ $errors->has('description') ? ' is-invalid' : '' }} id="description" rows="3" name="description">
                {{ old('description') }}
            </textarea>
            @if ($errors->has('description'))
                <span class="invalid-feedback"><strong>{{ $errors->first('description') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <label for="link" class="col-form-label">Add Book</label>
            <input id="link" type="file" class="form-control{{ $errors->has('link') ? ' is-invalid' : '' }}" name="link" value="{{ old('link') }}">
            @if ($errors->has('link'))
                <span class="invalid-feedback"><strong>{{ $errors->first('link') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <label for="author" class="col-form-label">Authors</label>
            <select id="author" class="form-control{{ $errors->has('authors') ? ' is-invalid' : '' }}" name="author">
                @foreach ($authors as $value => $label)
                    <option value="{{ $label->id }}">{{ $label->name . ' ' . $label->surname }}</option>
                @endforeach;
            </select>
            @if ($errors->has('authors'))
                <span class="invalid-feedback"><strong>{{ $errors->first('authors') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <label for="categories" class="col-form-label">Categories</label>
            <select id="categories" class="form-control{{ $errors->has('categories') ? ' is-invalid' : '' }}" name="categories[]"  multiple>
                @foreach ($categories as $key => $label)
                    <option value="{{ $catArray[] = $label->id }}">{{ $label->name }}</option>
                @endforeach;
            </select>
            @if ($errors->has('$categories'))
                <span class="invalid-feedback"><strong>{{ $errors->first('$categories') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/books/edit.blade.php
@extends('layouts.app')

@section('content')
{{--    @include('admin.users._nav')--}}

    <form method="POST" action="{{ route('admin.books.update', $book) }}">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="name" class="col-form-label">Name</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $book->name) }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" {{ $errors->has('description') ? ' is-invalid' : '' }} id="description" rows="3" name="description">
                {{ old('description', $book->description) }}
            </textarea>
            @if ($errors->has('description'))
                <span class="invalid-feedback"><strong>{{ $errors->first('description') }}</strong></span>
            @endif
        </div>
        <div class="d-flex">
            <div class="form-group mr-2">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>

        </div>
    </form>
    <form method="POST" action="{{ route('admin.books.delete', $book) }}">
        @csrf
        @method('DELETE')
        <div class="form-group">
            <button type="submit" class="btn btn-danger">Delete</button>
        </div>
    </form>
@endsection

resources/views/admin/books/index.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.books._nav')
    <div>
        <a href="{{ route('admin.books.create') }}" class="btn btn-success">
            Add Book
        </a>
    </div>

    @include('admin.books.searchAjax')
@endsection

resources/views/admin/books/searchAjax.blade.php
<div id="table_data">
    <div class="card mb-3">
        <div class="card-header">Filter</div>
        <div class="card-body">
            <div class="row">
                <div class="col-sm-1">
                    <div class="form-group">
                        <label for="categories" class="col-form-label">Category</label>
                        <input id="categories" class="form-control" name="categories">
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <label for="author" class="col-form-label">Author Surname</label>
                        <input id="author" class="form-control" name="author" >
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="form-group">
                        <label class="col-form-label">&nbsp;</label><br />
                        <button id="search" class="btn btn-primary">Search</button>
                    </div>
                </div>
            </div>
        </div>
    </div>


<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Link</th>
        <th>Categories</th>
        <th>Author</th>
    </tr>
    </thead>
    <tbody>

    @foreach ($books as $book)
        <tr>
            <td>{{ $book->id }}</td>
            <td><a href="{{ route('admin.books.show', $book) }}">{{ $book->name }}</a></td>
            <td><a href="{{ route('admin.books.show', $book) }}">{{ $book->description }}</a></td>
            <td>
                @if($book->link !== ' ')
                    <a href="{{ $book->link }}">Перейти</a>
                @endif
            </td>
            <td>
                @foreach ($book->categories as $category)
                    @if ($loop->iteration > 1)
                        |
                    @endif
                    {{ $category->name }}
                @endforeach
            </td>
            <td>
                {{ $book->author->name . ' ' . $book->author->surname }}
            </td>
        </tr>
    @endforeach

    </tbody>
</table>
</div>

resources/views/admin/books/show.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.users._nav')

    <div class="d-flex flex-row mb-3">
        <a href="{{ route('admin.books.edit', $book) }}" class="btn btn-primary mr-1">Edit</a>
    </div>

    <table class="table table-bordered table-striped">
        <tbody>
        <tr>
            <th>ID</th><td>{{ $book->id }}</td>
        </tr>
        <tr>
            <th>Name</th><td>{{ $book->name }}</td>
        </tr>
        <tr>
            <th>Description</th><td>{{ $book->description }}</td>
        </tr>
        <tr>
            <th>Link</th><td><a href="{{ $book->link }}">Перейти</a></td>
        </tr>
        <tbody>
        </tbody>
    </table>

@endsection