routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');


Auth::routes();

Route::group([
	'prefix' => 'admin',
	'as' => 'admin.',
	'namespace' => 'Admin',
	'middleware' => ['auth']
], function () {
	Route::get('/home', 'HomeController@index')->name('home');
	Route::group( [
		'prefix'    => 'author',
		'as'        => 'authors.',
	], function () {
		Route::get( '/', 'AuthorController@index' )->name( 'home' );
		Route::get( '/show/{author}', 'AuthorController@show' )->name( 'show' );
		Route::get( '/create', 'AuthorController@create' )->name( 'create' );
		Route::post( '/store', 'AuthorController@store' )->name( 'store' );
		Route::get( '/{author}/edit', 'AuthorController@edit' )->name( 'edit' );
		Route::put( '/{author}/update', 'AuthorController@update' )->name( 'update' );
		Route::delete( '/{author}/delete', 'AuthorController@destroy' )->name( 'delete' );
	});

	Route::group( [
		'prefix'    => 'book',
		'as'        => 'books.',
	], function () {
		Route::get( '/', 'BookController@index' )->name( 'index' );
		Route::get( '/ajax', 'BookController@index' )->name( 'searchAjax' );
		Route::get( '/show/{book}', 'BookController@show' )->name( 'show' );
		Route::get( '/create', 'BookController@create' )->name( 'create' );
		Route::post( '/store', 'BookController@store' )->name( 'store' );
		Route::get( '/{book}/edit', 'BookController@edit' )->name( 'edit' );
		Route::put( '/{book}/update', 'BookController@update' )->name( 'update' );
		Route::delete( '/{book}/delete', 'BookController@destroy' )->name( 'delete' );
	});

	Route::group( [
		'prefix'    => 'category',
		'as'        => 'categories.',
	], function () {
		Route::get( '/', 'CategoryController@index' )->name( 'index' );
		Route::get( '/show/{category}', 'CategoryController@show' )->name( 'show' );
		Route::get( '/create', 'CategoryController@create' )->name( 'create' );
		Route::post( '/store', 'CategoryController@store' )->name( 'store' );
		Route::get( '/{category}/edit', 'CategoryController@edit' )->name( 'edit' );
		Route::put( '/{category}/update', 'CategoryController@update' )->name( 'update' );
		Route::delete( '/{category}/delete', 'CategoryController@destroy' )->name( 'delete' );
	});
  });

app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entity\Author;
use App\Http\Requests\Author\CreateRequest;
use Exception;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\Response;

class AuthorController extends Controller
{
	/**
	 * Display a listing of the resource.
	 *
	 * @param Request $request
	 *
	 * @return Response
	 */
    public function index(Request $request)
    {
	    $query = Author::orderByDesc('id');
	    $query = Author::has('reviews','>','3');

	    if (!empty($value = $request->get('id'))) {
		    $query->where('id', $value);
	    }

	    if (!empty($value = $request->get('name'))) {
		    $query->where('name', 'like', '%' . $value . '%');
	    }

	    if (!empty($value = $request->get('surname'))) {
		    $query->where('role', 'like', '%' . $value . '%');
	    }

	    $authors = $query->paginate(20);


	    return view('admin.authors.index', compact('authors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
	    return view('admin.authors.create');
    }

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param CreateRequest $request
	 *
	 * @return Response
	 */
    public function store(CreateRequest $request)
    {
	    $author = Author::create(
	    	[
			    'name'  => $request['name'],
			    'surname' => $request['surname'],
			    'biography' => $request['biography'],
		    ]
	    );

	    return redirect()->route('admin.authors.show', $author);
    }

	/**
	 * Display the specified resource.
	 *
	 * @param Author $author
	 *
	 * @return Response
	 */
    public function show(Author $author)
    {
	    return view('admin.authors.show', compact('author'));
    }

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param Author $author
	 *
	 * @return Response
	 */
    public function edit(Author $author)
    {
	    return view('admin.authors.edit', compact('author'));
    }

	/**
	 * Update the specified resource in storage.
	 *
	 * @param CreateRequest $request
	 * @param Author $author
	 *
	 * @return void
	 */
    public function update(CreateRequest $request, Author $author)
    {
	    $author->update([
		    'name' => $request['name'],
		    'surname' => $request['surname'],
		    'biography' => $request['biography'],
	    ]);

	    return redirect()->route('admin.authors.show', $author);
    }

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param Author $author
	 *
	 * @return void
	 * @throws Exception
	 */
    public function destroy(Author $author)
    {
	    $author->delete();

	    return redirect()->route('admin.authors.home');
    }
}

resources/views/admin/authors/_nav.blade.php
@include ('admin._nav', ['page' => 'users'])

resources/views/admin/authors/create.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.users._nav')

    <form method="POST" action="{{ route('admin.authors.store') }}">
        @csrf

        <div class="form-group">
            <label for="name" class="col-form-label">Name</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="surname" class="col-form-label">Surname</label>
            <input id="surname" type="text" class="form-control{{ $errors->has('surname') ? ' is-invalid' : '' }}" name="surname" value="{{ old('surname') }}" required>
            @if ($errors->has('surname'))
                <span class="invalid-feedback"><strong>{{ $errors->first('surname') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <label for="biography">Biography</label>
            <textarea class="form-control" {{ $errors->has('biography') ? ' is-invalid' : '' }} id="biography" rows="3" name="biography">
                {{ old('biography') }}
            </textarea>
            @if ($errors->has('biography'))
                <span class="invalid-feedback"><strong>{{ $errors->first('biography') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/authors/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.users._nav')

    <form method="POST" action="{{ route('admin.authors.update', $author) }}">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="name" class="col-form-label">Name</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $author->name) }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>

        <div class="form-group">
            <label for="surname" class="col-form-label">Surname</label>
            <input id="surname" type="text" class="form-control{{ $errors->has('surname') ? ' is-invalid' : '' }}" name="surname" value="{{ old('surname', $author->surname) }}" required>
            @if ($errors->has('surname'))
                <span class="invalid-feedback"><strong>{{ $errors->first('surname') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <label for="biography">Biography</label>
            <textarea class="form-control" {{ $errors->has('biography') ? ' is-invalid' : '' }} id="biography" rows="3" name="biography">
                {{ old('biography', $author->biography) }}
            </textarea>
            @if ($errors->has('biography'))
                <span class="invalid-feedback"><strong>{{ $errors->first('biography') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
    <form method="POST" action="{{ route('admin.authors.delete', $author) }}">
        @csrf
        @method('DELETE')
        <div class="form-group">
            <button type="submit" class="btn btn-danger">Delete</button>
        </div>
    </form>
@endsection

resources/views/admin/authors/index.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.authors._nav')
    <div>
        <a href="{{ route('admin.authors.create') }}" class="btn btn-success">
            Add Author
        </a>
    </div>
    <div class="card mb-3">
        <div class="card-header">Filter</div>
        <div class="card-body">
            <form action="?" method="GET">
                <div class="row">
                    <div class="col-sm-1">
                        <div class="form-group">
                            <label for="id" class="col-form-label">ID</label>
                            <input id="id" class="form-control" name="id" value="{{ request('id') }}">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="name" class="col-form-label">Name</label>
                            <input id="name" class="form-control" name="name" value="{{ request('name') }}">
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label for="email" class="col-form-label">Surname</label>
                            <input id="email" class="form-control" name="email" value="{{ request('email') }}">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label class="col-form-label">&nbsp;</label><br />
                            <button type="submit" class="btn btn-primary">Search</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Status</th>
            <th>Role</th>
        </tr>
        </thead>
        <tbody>

        @foreach ($authors as $author)
            <tr>
                <td>{{ $author->id }}</td>
                <td><a href="{{ route('admin.authors.show', $author) }}">{{ $author->name }}</a></td>
                <td><a href="{{ route('admin.authors.show', $author) }}">{{ $author->surname }}</a></td>
                <td>
                   {{ $author->biography }}
                </td>
            </tr>
        @endforeach

        </tbody>
    </table>


    {{ $authors->links() }}
@endsection

resources/views/admin/authors/show.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.users._nav')

    <div class="d-flex flex-row mb-3">
        <a href="{{ route('admin.authors.edit', $author) }}" class="btn btn-primary mr-1">Edit</a>
    </div>

    <table class="table table-bordered table-striped">
        <tbody>
        <tr>
            <th>ID</th><td>{{ $author->id }}</td>
        </tr>
        <tr>
            <th>Name</th><td>{{ $author->name }}</td>
        </tr>
        <tr>
            <th>Surname</th><td>{{ $author->surname }}</td>
        </tr>
        <tr>
            <th>Biography</th><td>{{ $author->biography }}</td>
        </tr>
        <tbody>
        </tbody>
    </table>

@endsection