routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index')->name('home');


Auth::routes();

Route::group([
	'prefix' => 'admin',
	'as' => 'admin.',
	'namespace' => 'Admin',
	'middleware' => ['auth']
], function () {
	Route::get('/home', 'HomeController@index')->name('home');
	Route::group( [
		'prefix'    => 'author',
		'as'        => 'authors.',
	], function () {
		Route::get( '/', 'AuthorController@index' )->name( 'home' );
		Route::get( '/show/{author}', 'AuthorController@show' )->name( 'show' );
		Route::get( '/create', 'AuthorController@create' )->name( 'create' );
		Route::post( '/store', 'AuthorController@store' )->name( 'store' );
		Route::get( '/{author}/edit', 'AuthorController@edit' )->name( 'edit' );
		Route::put( '/{author}/update', 'AuthorController@update' )->name( 'update' );
		Route::delete( '/{author}/delete', 'AuthorController@destroy' )->name( 'delete' );
	});

	Route::group( [
		'prefix'    => 'book',
		'as'        => 'books.',
	], function () {
		Route::get( '/', 'BookController@index' )->name( 'index' );
		Route::get( '/ajax', 'BookController@index' )->name( 'searchAjax' );
		Route::get( '/show/{book}', 'BookController@show' )->name( 'show' );
		Route::get( '/create', 'BookController@create' )->name( 'create' );
		Route::post( '/store', 'BookController@store' )->name( 'store' );
		Route::get( '/{book}/edit', 'BookController@edit' )->name( 'edit' );
		Route::put( '/{book}/update', 'BookController@update' )->name( 'update' );
		Route::delete( '/{book}/delete', 'BookController@destroy' )->name( 'delete' );
	});

	Route::group( [
		'prefix'    => 'category',
		'as'        => 'categories.',
	], function () {
		Route::get( '/', 'CategoryController@index' )->name( 'index' );
		Route::get( '/show/{category}', 'CategoryController@show' )->name( 'show' );
		Route::get( '/create', 'CategoryController@create' )->name( 'create' );
		Route::post( '/store', 'CategoryController@store' )->name( 'store' );
		Route::get( '/{category}/edit', 'CategoryController@edit' )->name( 'edit' );
		Route::put( '/{category}/update', 'CategoryController@update' )->name( 'update' );
		Route::delete( '/{category}/delete', 'CategoryController@destroy' )->name( 'delete' );
	});
  });

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Entity\Category;
use App\Http\Requests\Category\CreateCategoryRequest;
use App\Http\Controllers\Controller;
use Illuminate\Http\Response;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
	    $query = Category::orderByDesc('id');

	    $categories = $query->paginate(20);

	    return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
	    return view('admin.categories.create');
    }

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param CreateCategoryRequest $request
	 *
	 * @return Response
	 */
    public function store(CreateCategoryRequest $request)
    {
	    $category = Category::create(
		    [
			    'name'  => $request['name'],
		    ]
	    );

	    return redirect()->route('admin.categories.show', $category);
    }

	/**
	 * Display the specified resource.
	 *
	 * @param Category $category
	 *
	 * @return Response
	 */
    public function show(Category $category)
    {
	    return view('admin.categories.show', compact('category'));
    }

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param Category $category
	 *
	 * @return void
	 */
    public function edit(Category $category)
    {
	    return view('admin.categories.edit', compact('category'));
    }

	/**
	 * Update the specified resource in storage.
	 *
	 * @param CreateCategoryRequest $request
	 * @param Category $category
	 *
	 * @return Response
	 */
    public function update(CreateCategoryRequest $request, Category $category)
    {
	    $category->update(
		    [
			    'name'  => $request['name'],
		    ]
	    );
	    return redirect()->route('admin.categories.show', $category);
    }

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param Category $category
	 *
	 * @return Response
	 * @throws \Exception
	 */
    public function destroy(Category $category)
    {
	    $category->delete();

	    return redirect()->route('admin.categories.index');
    }
}

resources/views/admin/categories/_nav.blade.php
@include ('admin._nav', ['page' => 'users'])

resources/views/admin/categories/create.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.users._nav')

    <form method="POST" action="{{ route('admin.categories.store') }}">
        @csrf

        <div class="form-group">
            <label for="name" class="col-form-label">Name</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.users._nav')

    <form method="POST" action="{{ route('admin.books.update', $category) }}">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="name" class="col-form-label">Name</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $category->name) }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
    <form method="POST" action="{{ route('admin.categories.delete', $category) }}">
        @csrf
        @method('DELETE')
        <div class="form-group">
            <button type="submit" class="btn btn-danger">Delete</button>
        </div>
    </form>
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.books._nav')
    <div>
        <a href="{{ route('admin.categories.create') }}" class="btn btn-success">
            Add Category
        </a>
    </div>
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
        </tr>
        </thead>
        <tbody>

        @foreach ($categories as $category)
            <tr>
                <td>{{ $category->id }}</td>
                <td><a href="{{ route('admin.categories.show', $category) }}">{{ $category->name }}</a></td>
            </tr>
        @endforeach

        </tbody>
    </table>


    {{ $categories->links() }}
@endsection

resources/views/admin/categories/show.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.users._nav')

    <div class="d-flex flex-row mb-3">
        <a href="{{ route('admin.categories.edit', $category) }}" class="btn btn-primary mr-1">Edit</a>
    </div>

    <table class="table table-bordered table-striped">
        <tbody>
        <tr>
            <th>ID</th><td>{{ $category->id }}</td>
        </tr>
        <tr>
            <th>Name</th><td>{{ $category->name }}</td>
        </tr>
        <tbody>
        </tbody>
    </table>

@endsection